blog/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from blog.views import Main, Posts, post, About, Contact, Thanks
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', Main),
    url(r'^blog/$', Posts),
    url(r'^about/$', About),
    url(r'^contact/$', Contact),
    url(r'^contact/thanks/$', Thanks),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/(?P<slug>[-\w]+)/$', post),
	url(r'^ckeditor/', include('ckeditor.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models
from blog import settings
from ckeditor.fields import RichTextField
from markdown import markdown



class Post(models.Model):
	title = models.CharField(max_length=100)
	description = models.TextField(null=True, blank=True)
	pub_date = models.DateTimeField()
	text = RichTextField()
	link_to_image = models.CharField("Link to image", max_length=100)
	slug = models.SlugField(max_length=40, blank=True)
	display = models.BooleanField(default=True)
	
	def __unicode__(self):
		return self.title

	
	class Meta:
		#default ordering
		ordering = ["pub_date"]

	

	

blog/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField()
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render
from blog.models import Post

from blog.forms import ContactForm
from django.core.mail import send_mail
from django.http import HttpResponseRedirect


def Main(request):
	lastest_posts = Post.objects.filter(display=True).order_by("-pub_date",) [:2]
	return render(request, "main.html", {"lastest_posts": lastest_posts, })

def Posts(request): # list of Posts in blog
	posts = Post.objects.all().order_by("-pub_date")
	return render(request, "blog.html", {"posts" : posts,})

def post(request, slug):
	post = Post.objects.get(slug=slug) ## Atvaizduoja atitinkama posta pagal slug.
										## Apparently skirtinguose viewsuose galima
										## naudoti vienodus vardus.
	return render(request, "post.html", {"post" : post})

def About(request):
	post = Post.objects.get(title = "About")
	return render(request, "about.html", {"post" : post})


def Contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['eimantas.stonys@gmail.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'form': form})

def Thanks(request):
    return render(request, "thanks.html",)

blog/templates/about.html
<!-- TOP, social, Contact, post, img.ctr?,  -->

{% extends "main.html" %}

{% block Content %}

<div id="blog_wrap">
<div id="post">



<h1 class="post"><a href="">{{ post.title }}</a></h1>
<p><b>{{ post.description }}</b></p>
{% if post.link_to_image %}
<div id="blog_img"><img src="{{ post.link_to_image }}" border="0" alt="Powered by Django." title="Powered by Django." /></a></div>
{% endif %}


{{ post.text|safe }}







</div>
</div>

{% endblock %}

blog/templates/blog.html
{% extends "main.html" %}

{% block Content %}
<div id="content"><p>You can read some entries by me here.</p></div>

<div id="blog_wrap">
<div id="blog_recent">

{% for post in posts %}
{% if post.display %}
<h1 class="frontpage"><a href="{{ post.slug }}">{{ post.title }}</a></h1>
<p class = "pub_date">{{ post.pub_date }}</p>
<p>{{ post.description }}</p>
<hr>
{% endif %}
{% endfor %}

</div>
</div>

{% endblock %}

blog/templates/contact.html
{% extends "main.html" %}

{% block Content %}

<div id="content"><p>You can contact me here.</p></div>

<div id="blog_wrap">
<div id="post">

<!--{% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}-->

    <form action="" method="post">
        <div id="field">
            
            <label for="id_subject">Subject:</label><br>
            {{ form.subject }}
            {{ form.subject.errors.as_text }}
            <br>

            <label for="id_email">Your e-mail address:</label><br>
            {{ form.email }}
            {{ form.email.errors.as_text }}<br>
            
            <label for="id_message">Message:</label><br>
            {{ form.message }}
            {{ form.message.errors.as_text }}
        
        {% csrf_token %}
        <br><input type="submit" value="Say Hello">
    </div>
    </form>
    <br>


{% endblock %}

blog/templates/hello.html
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}styles.css">
	<div id=content>
		<p>
		 <span style="font-weight: bold">Hello there.</span><br><br>
		 My name is <a href="mailto:eimantas.stonys@gmail.com">Eimantas Stonys.</a><br>
		 I work as a graphic / layout designer<br>in a Norwegian company called
		 <a href="http://www.instant.no/">Instant Norge AS.</a><br>
		 I am also trying to learn <a href="http://www.python.org/">Python</a>
		 and its framework <a href="http://www.djangoproject.com/">Django</a>.
		</p>
	</div>

blog/templates/index.html
This is a template

blog/templates/main.html
<!DOCTYPE html>

<html>

<head>
	<!--<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
	<script>

	var offset = 10%; // left offset of the fixed div (without scrolling)

$(document).scroll(function(e) {
    // b is the fixed div
    $('#menu').css({
        'left': offset - $(document).scrollLeft()
    });
});

	</script>-->
	<title>Hello</title>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}style.css"/>
	<link href="{{ STATIC_URL }}monokai.css" media="screen" rel="stylesheet" type="text/css" />

</head>

<body>
 	<div id="wrap">
 		<div id="pic"><a href="/"><img src="{{ STATIC_URL }}images/ash.png"></img></a><br></div>
  		 {% block Nav %}




  		<div id="menu">
  			<div class="first"><a href="/about">About</a></div><br>
  			<div class="second"><a href="#">Apps</a></div><br>
  			<div class="third"><a href="/blog">Blog</a></div><br>
  			<div class="fifth"><a href="/contact">Contact</a></div>
  		</div>
  		{% endblock %}

  		{% block Content %}
	  	<div id="content">
			<p>
			Hello there. My name is <a href="mailto:eimantas.stonys@gmail.com">Eimantas Stonys.</a>
			I work as a graphic / layout designer
			in a Norwegian company called
			<a href="http://www.instant.no">Instant Norge AS.</a>
			I am also trying to learn <a href="http://www.python.org/">Python</a>
			and its framework <a href="http://www.djangoproject.com/">Django.</a><br><br>
			You can find some of my recent projects here.
			You can also browse my graphic design gallery.
			I do not write much, but you can read some of my blog entries
			in this small Django-based website.
			</p>
			</div>

			<div id="apps_wrap">
			<div id="apps_ribbon"></div>
			<div id="apps_recent">
			<p>
			<h1 class="frontpage"><a href="#">Snappy</a></h1>
			<p>Project description...</p><hr>
			<h1 class="frontpage"><a href="#">Heroku</a></h1>
			<p>Project description...</p>
			</p>
			</div>
		</div>

			<div id="blog_wrap">
			<div id="blog_ribbon"></div>
			<div id="blog_recent">

			{% for lastest_post in lastest_posts %}
			{% if lastest_post.display %}
			<h1 class="frontpage"><a href="/blog/{{ lastest_post.slug }}">{{ lastest_post.title }}</a></h1>
			<p class = "pub_date">{{ lastest_post.pub_date }}</p>
			<p style= "text-decoration: none;">{{ lastest_post.description|safe }}</p>
			{% endif %}
			{% endfor %}

			</div>
			</div>

		
		{% endblock %}



  	</div>
</body>

</html>

blog/templates/post.html
<!-- TOP, social, Contact, About, img.ctr?,  -->

{% extends "main.html" %}

{% block Content %}

<div id="blog_wrap">
<div id="post">



<h1 class="post"><a href="">{{ post.title }}</a></h1>
<p class = "pub_date">{{ post.pub_date }}</p>
<p><b>{{ post.description }}</b></p>
{% if post.link_to_image %}
<div id="blog_img"><img src="{{ post.link_to_image }}" border="0" alt="Powered by Django." title="Powered by Django." /></a></div>
{% endif %}



{% load pygmentify %}
{% pygment %}

{{ post.text|safe }}

{% endpygment %}





</div>
</div>

{% endblock %}

blog/templates/test.html
<!DOCTYPE html>

<html>

<head>
	<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}style.css"/>
</head>

<body>
 	<div id="wrap">
 		<div id="pic"><a href="/main"><img src="{{ STATIC_URL }}/images/1_g.png"></img></a><br></div>
  		 {% block Nav %}
  		<div id="menu">
  			<div class="first"><a href="http://www.google.lt">About</a></div><br>
  			<div class="second"><a href="http://www.google.lt">Apps</a></div><br>
  			<div class="third"><a href="/blog">Blog</a></div><br>
  			<div class="fourth"><a href="http://www.google.lt">Design</a></div><br>
  			<div class="fifth"><a href="http://www.google.lt">Contact</a></div>
  		</div>
  		{% endblock %}

  		{% block Content %}
	  	<div id="content">
			<p>
			aaa
			</p>
			</div>

			<div id="apps_wrap">
			<div id="apps_ribbon"></div>
			<div id="apps_recent">
			<p>
			<h1 class="frontpage"><a href="http://www.google.lt">Snappy</a></h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ornare ante eget arcu euismod ultricies. Pellentesque semper leo massa, at tincidunt nibh sodales ac. </p><hr>
			<h1 class="frontpage"><a href="http://www.google.lt">Heroku</a></h1>
			<p>Project description...</p>
			</p>
			</div>
		</div>

			<div id="blog_wrap">
			<div id="blog_ribbon"></div>
			<div id="blog_recent">
			<h1 class="frontpage"><a href="http://www.google.lt">Blog entry title</a></h1>
			<p>This is an article...</p><hr>
			<h1 class="frontpage"><a href="http://www.google.lt">Another blog entry</a></h1>
			<p>This is an article...</p>
			</div>
			</div>

			<div id="design_wrap">
			<div id="design_ribbon"></div>
			<div id="design_recent">
			<div id="design_recent_1"><p>Picture No. 1</p></div>
			<div id="design_recent_2"><p>Picture No. 2</p></div>
			<div id="design_recent_3"><p>Picture No. 3</p></div>
			</div>
			</div>
		{% endblock %}



  	</div>
</body>

</html>

blog/templates/thanks.htm
{% extends "main.html" %}

{% block Content %}

<div id="content"><p>You can contact me here.</p></div>

<div id="blog_wrap">
<div id="post">

<!--{% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}-->

    <form action="" method="post">
        <div id="field">
            
            <label for="id_subject">Subject:</label><br>
            {{ form.subject }}
            {{ form.subject.errors.as_text }}
            <br>

            <label for="id_email">Your e-mail address:</label><br>
            {{ form.email }}
            {{ form.email.errors.as_text }}<br>
            
            <label for="id_message">Message:</label><br>
            {{ form.message }}
            {{ form.message.errors.as_text }}
        
        {% csrf_token %}
        <br><input type="submit" value="Send!">
    </div>
    </form>
    <br>


{% endblock %}

blog/templates/thanks.html
{% extends "main.html" %}

{% block Content %}



<div id="blog_wrap">
<div id="post">

<p>Thanks</p>

    </div>
    </form>
    <br>


{% endblock %}